%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('p:CancelTransaction', {anyAttribs, 'TransactionId'}).
-record('p:CancelTransactionResponse', {anyAttribs, 'Result'}).
-record('p:ChargeAmount', {anyAttribs, 'AccountNumber', 'Amount'}).
-record('p:ChargeAmountResponse', {anyAttribs, 'Result'}).
-record('p:ConfirmTransaction', {anyAttribs, 'TransactionId'}).
-record('p:ConfirmTransactionResponse', {anyAttribs, 'Result'}).
-record('p:RefillAmount', {anyAttribs, 'AccountNumber', 'Amount'}).
-record('p:RefillAmountResponse', {anyAttribs, 'Result'}).
-record('p:ReserveAmount', {anyAttribs, 'AccountNumber', 'Amount'}).
-record('p:ReserveAmountResponse', {anyAttribs, 'Result'}).
-record('soap:Body', {anyAttribs, choice}).
-record('soap:Envelope', {anyAttribs, 'Header', 'Body', choice}).
-record('soap:Fault', {anyAttribs, 'faultcode', 'faultstring', 'faultactor', 'detail'}).
-record('soap:Header', {anyAttribs, choice}).
-record('soap:detail', {anyAttribs, choice}).
